Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.network "forwarded_port", guest: 80, host: 8081

  # Dossier synchronisé
  config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.gui = false  # Désactiver la GUI
  end

  # Provisionnement Shell
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y vim nginx git console-data

    # Modifier la configuration de Nginx pour servir /var/www
    sudo sed -i 's|root /var/www/html;|root /var/www;|' /etc/nginx/sites-available/default
    sudo systemctl restart nginx
  SHELL
end
